// Ignore this file to prevent zz_generated for this package
//go:build !ignore_autogenerated

//go:generate go run github.com/j2gg0s/godefault/main.go -i github.com/j2gg0s/godefault/examples/output_tests/... -o . --trim-path-prefix=github.com/j2gg0s/godefault/examples/output_tests
package output_tests_test

import (
	_ "github.com/j2gg0s/godefault/cmd/godefault"
)
